# Values used for the deployed application.
replicaCount: 2
service:
  name: content-rw-elasticsearch
env:
  KAFKA_TOPIC: CombinedPostPublicationEvents
  KAFKA_CONCURRENT_PROCESSING: false
  PUBLIC_CONCORDANCES_ENDPOINT: http://public-concordances-api:8080
