concepts:
  organisation: "http://www.ft.com/ontology/organisation/Organisation"
  person: "http://www.ft.com/ontology/person/Person"
  company: "http://www.ft.com/ontology/company/Company"
  brand: "http://www.ft.com/ontology/product/Brand"
  topic: "http://www.ft.com/ontology/Topic"
  location: "http://www.ft.com/ontology/Location"
  genre: "http://www.ft.com/ontology/Genre"

predicates:
  isPrimaryClassifiedBy: "http://www.ft.com/ontology/classification/isPrimarilyClassifiedBy"
  isClassifiedBy: "http://www.ft.com/ontology/classification/isClassifiedBy"
  implicitlyClassifiedBy: "http://www.ft.com/ontology/implicitlyClassifiedBy"
  about: "http://www.ft.com/ontology/annotation/about"
  implicitlyAbout: "http://www.ft.com/ontology/implicitlyAbout"
  mentions: "http://www.ft.com/ontology/annotation/mentions"
  majorMentions: "http://www.ft.com/ontology/annotation/majorMentions"
  hasDisplayTag: "http://www.ft.com/ontology/hasDisplayTag"
  hasAuthor: "http://www.ft.com/ontology/annotation/hasAuthor"
  hasContributor: "http://www.ft.com/ontology/hasContributor"

content:
  origin:
    methode: "methode-web-pub"
    wordpress: "wordpress"
    video: "next-video-editor"
    pac: "http://cmdb.ft.com/systems/pac"

authorities:
  article: "http://api.ft.com/system/FTCOM-METHODE"
  blog: "http://api.ft.com/system/FT-LABS-WP"
  video: "http://api.ft.com/system/NEXT-VIDEO-EDITOR"

esContentTypeMap:
  article:
    collection: "FTCom"
    format: "Articles"
    category: "article"
  blog:
    collection: "FTBlogs"
    format: "Blogs"
    category: "blogPost"
  video:
    collection: "FTVideos"
    format: "Videos"
    category: "video"
  audio:
    collection: "FTAudios"
    format: "Audios"
    category: "audio"
